### ISSUE TITLE
Exception: java.lang.NoSuchMethodError: java.util.List org.bson.Document.getList

### ISSUE THREAD

**Issue by devheroo** [alexandru-slobodcicov/liquibase-nosql-quickstart#1]
Hello,
I am not able to run the MongoDB examples and I feel like I am missing something simple here.
When I run any liquibase command (liquibase dropAll | update), I get this exception:
`java.lang.NoSuchMethodError: 'java.util.List org.bson.Document.getList(java.lang.Object, java.lang.Class)'

I tried with JDK 1.8 , 11 and 16.

Here is a complete log:
`Starting Liquibase at 14:49:21 (version 4.3.5 #62 built at 2021-04-29 18:31+0000)
[2021-05-28 14:49:21] INFO [com.mongodb.diagnostics.logging.JULLogger log] Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='1000 ms', maxWaitQueueSize=500}
[2021-05-28 14:49:21] INFO [com.mongodb.diagnostics.logging.JULLogger log] Opened connection [connectionId{localValue:1, serverValue:1626}] to localhost:27017
[2021-05-28 14:49:21] INFO [com.mongodb.diagnostics.logging.JULLogger log] Monitor thread successfully connected to server with description ServerDescription{address=localhost:27017, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[4, 0, 22]}, minWireVersion=0, maxWireVersion=7, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=2040931}
[2021-05-28 14:49:21] INFO [com.mongodb.diagnostics.logging.JULLogger log] Opened connection [connectionId{localValue:2, serverValue:1627}] to localhost:27017
[2021-05-28 14:49:21] INFO [liquibase.ext] Successfully released change log lock
[2021-05-28 14:49:21] INFO [com.mongodb.diagnostics.logging.JULLogger log] Closed connection [connectionId{localValue:2, serverValue:1627}] to localhost:27017 because the pool has been closed.
Unexpected error running Liquibase: 'java.util.List org.bson.Document.getList(java.lang.Object, java.lang.Class)'
For more information, please use the --logLevel flag
[2021-05-28 14:49:21] SEVERE [liquibase.integration] Unexpected error running Liquibase: 'java.util.List org.bson.Document.getList(java.lang.Object, java.lang.Class)'
java.lang.NoSuchMethodError: 'java.util.List org.bson.Document.getList(java.lang.Object, java.lang.Class)'
        at liquibase.ext.mongodb.statement.AbstractRunCommandStatement.checkResponse(AbstractRunCommandStatement.java:78)
        at liquibase.ext.mongodb.statement.AbstractRunCommandStatement.run(AbstractRunCommandStatement.java:60)
        at liquibase.ext.mongodb.statement.AbstractRunCommandStatement.run(AbstractRunCommandStatement.java:55)
        at liquibase.ext.mongodb.statement.ListCollectionNamesStatement.queryForList(ListCollectionNamesStatement.java:79)
        at liquibase.ext.mongodb.statement.CountCollectionByNameStatement.queryForLong(CountCollectionByNameStatement.java:44)
        at liquibase.ext.mongodb.statement.CountCollectionByNameStatement.queryForLong(CountCollectionByNameStatement.java:33)
        at liquibase.nosql.executor.NoSqlExecutor.queryForLong(NoSqlExecutor.java:105)
        at liquibase.nosql.executor.NoSqlExecutor.queryForLong(NoSqlExecutor.java:98)
        at liquibase.ext.mongodb.lockservice.MongoLockService.existsRepository(MongoLockService.java:85)
        at liquibase.nosql.lockservice.AbstractNoSqlLockService.hasDatabaseChangeLogLockTable(AbstractNoSqlLockService.java:305)
        at liquibase.nosql.lockservice.AbstractNoSqlLockService.releaseLock(AbstractNoSqlLockService.java:197)
        at liquibase.command.core.DropAllCommand.run(DropAllCommand.java:147)
        at liquibase.command.AbstractCommand.execute(AbstractCommand.java:19)
        at liquibase.integration.commandline.Main.doMigration(Main.java:1753)
        at liquibase.integration.commandline.Main$1.lambda$run$0(Main.java:367)
        at liquibase.Scope.lambda$child$0(Scope.java:160)
        at liquibase.Scope.child(Scope.java:169)
        at liquibase.Scope.child(Scope.java:159)
        at liquibase.Scope.child(Scope.java:138)
        at liquibase.integration.commandline.Main$1.run(Main.java:366)
        at liquibase.integration.commandline.Main$1.run(Main.java:196)
        at liquibase.Scope.child(Scope.java:169)
        at liquibase.Scope.child(Scope.java:145)
        at liquibase.integration.commandline.Main.run(Main.java:196)
        at liquibase.integration.commandline.Main.main(Main.java:158)`

**Comment by tomagb** [comment]
Have you been able to go past this error?
